version: "3"
services:
 app:
   container_name: pellizzaro_app
   build: .
   command: nodemon --watch /usr/src/app -e js app.js
   ports:
     - "3000:3000"
   volumes:
     - ./app:/usr/src/app
   links:
     - "mongo:mongohost"
 mongo:
   container_name: mongodb_pellizzaro_app
   image: mongo:latest
   volumes:
     - ./data:/data/db
   ports:
     - '27017:27017'
     